//
//  NewsDetailsModels.swift
//  CleanSwift
//
//  Created by Igor Dikan on 01.12.2020.
//  Copyright (c) 2020 Игорь Дикань. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsDetails {
    
    enum Something {
        struct Request {
            enum RequestType {
                case fetchDetails
            }
        }
        struct Response {
            enum ResponseType {
                case presentDetails(details: NewsCellModel)
            }
        }
        struct ViewModel{
            enum ViewModelData {
                case displayDetails(details: NewsCellModel)
            }
        }
    }
}
